# Generated by Django 4.1.7 on 2023-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
