# Generated by Django 4.1.7 on 2023-04-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacancy_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='main',
        ),
    ]
